CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    CPF VARCHAR(11) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100),
    TYPE INT,
    BALANCE DECIMAL(10, 2) DEFAULT 0.00
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (CPF);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    USER_VALUE DECIMAL(10, 2),
    CREATED_AT TIMESTAMP DEFAULT now(),
    FOREIGN KEY (PAYER) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS(ID)
);